### ISSUE TITLE
composer.json missing author error

### ISSUE THREAD

**Issue by juanjosezg** [krzysiekpiasecki/Symfonator#4]
The authors name is missing and when you try to run "composer install"  got this

 "./composer.json" does not match the expected JSON schema:
   - authors[0].name : The property name is required.

**Comment by krzysiekpiasecki** [comment]
@juanjosezg Can't reproduce. May I ask you to provide, how to reproduce it - in details ?

**Comment by krzysiekpiasecki** [comment]
@juanjosezg Please reopen this ticket, if you find, that it wasn't resolved properly. Thanks for the reporting me.
