### ISSUE TITLE
Error when running webpack 

### ISSUE THREAD

**Issue by petroccoC** [krzysiekpiasecki/Symfonator#7]
Hi. I have an error when i try running webpack to regenerate bundle. 
Command:
`./node_modules/.bin/encore dev --watch`

Stacktrace:
`ERROR  Failed to compile with 2 errors                                                                                             3:49:19 PM

 error  in ./src/scss/index.scss

Module build failed: 
@import 'vendor/index';
^
      File to import not found or unreadable: vendor/index.
Parent style sheet: stdin
      in /home/clap/Desktop/symfonator/src/scss/index.scss (line 6, column 1)

 @ ./src/scss/index.scss 4:14-200
 @ ./src/app.js

 error  in ./src/scss/index.scss

Module build failed: ModuleBuildError: Module build failed: 
@import 'vendor/index';
^
      File to import not found or unreadable: vendor/index.
Parent style sheet: stdin
      in /home/clap/Desktop/symfonator/src/scss/index.scss (line 6, column 1)
    at runLoaders (/home/clap/Desktop/symfonator/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/clap/Desktop/symfonator/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/clap/Desktop/symfonator/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/clap/Desktop/symfonator/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/clap/Desktop/symfonator/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/home/clap/Desktop/symfonator/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/home/clap/Desktop/symfonator/node_modules/async/dist/async.js:958:16)
    at options.error (/home/clap/Desktop/symfonator/node_modules/node-sass/lib/index.js:294:32)`

i also tried to clone again the repo but i encountered the same error. Any tips?

**Comment by ghost** [comment]
I got same issue, so i can't run npm install as Encore isn't configured. Did you solved this? It's (obviously) is fixed by removing vendor import, as there is no such folder in scss, but it's still strange, maybe on some step of installation it should be copied over there.

**Comment by petroccoC** [comment]
I deleted that import and reworked the scss section

**Comment by ghost** [comment]
I can't launch npm build, it fails with issue "Symfony Encore can't be called as it's not configured yet), webpack config line throws that. I deleted that import too. What did you changed?

**Comment by krzysiekpiasecki** [comment]
@petroccoC Did you fix it?

**Comment by petroccoC** [comment]
@PavelLJ i didn't have that error. Did you try composer update after composer create command?
@krzysiekpiasecki i fixed by removing this  @import 'vendor/index'; in index.scss

**Comment by krzysiekpiasecki** [comment]
@PavelLJ i didn't have that error too.

**Comment by bstaniszczak** [comment]
I have this error to, in file:
src/scss/index.scss
in line 6:
@import 'vendor/index';
but there is no folder
vendor with file index.scss

----------------------------

OK, the solution is getting this folder from Adminator:
https://github.com/puikinsh/Adminator-admin-dashboard/tree/master/src/assets/styles
I don't recomment to comment  this line:
@import 'vendor/index';
because images from the menu and the top search panel will disappear during compilation.
