### ISSUE TITLE
SQL statements to create important tables?

### ISSUE THREAD

**Issue by ghost** [krzysiekpiasecki/Symfonator#8]
I was a little bit confused when on user setup I understood that user table didn't exist and I don't know which format is needed. It would be far more convenient for beginners to have .sql file to make database ready for app requests. Nice work by the way.
P.S add Symfony/http-foundation requirement to pass security check script.

**Comment by krzysiekpiasecki** [comment]
> P.S add Symfony/http-foundation requirement to pass security check script.

Fixed with ddad69acdd730a6ce641aa2ec02936a51c7d6bef. @PavelLJ thanks.

**Comment by krzysiekpiasecki** [comment]
There was a missing shell command `bin/console doctrine:schema:create`
 at README.md.

@PavelLJ thanks.
